source/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::group(['prefix' => LaravelLocalization::setLocale()], function() {

    Route::get('/', 'IndexController@index');
    //function () {
    //    return view('index');
    //});


    Route::get('/official-rules', [
        'uses' => 'IndexController@rules',
        'as' => 'rules'
    ]);
    //[ 'as' => 'rules', function () {
    //    return view('rules');
    //}]);

});


Route::get('gallery', 'GalleryController@index');


// Admin Panel
Route::group(['namespace' => 'Admin', 'middleware' => 'goldfish.admin'], function() {

    Route::group(['middleware' => 'auth', 'prefix' => 'admin'], function() {

        Route::get('dashboard', [
            'as'			=> 'admin.dashboard',
            'uses' 			=> 'DashboardController@index'
        ]);

        // Manually trigger Instagram import
        Route::get('import-instagram', [
            'as'			=> 'admin.instagram',
            'uses' 			=> 'DashboardController@importInstagram'
        ]);

        // Manually trigger Twitter import
        Route::get('import-twitter', [
            'as'			=> 'admin.twitter',
            'uses' 			=> 'DashboardController@importTwitter'
        ]);

        Route::get('posts/moderate', [
            'as'            => 'admin.posts.moderation',
            'uses'          => 'PostsController@moderation'
        ]);
        Route::post('posts/{id}/moderate', 'PostsController@moderate');
        Route::post('posts/{id}/winners', 'PostsController@winners');
        Route::resource('posts', 'PostsController', ['only' => ['index']]);
        Route::resource('inspired_content', 'InspiredContentController');
    });

    // Admin Login/Logout (This needs to come after the rules above, and out of the middleware)
    Route::controller('admin', 'AuthController');

});

source/app/Http/Controllers/Admin/InspiredContentController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Storage;

use Brandmovers\Social\Post;


class InspiredContentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $posts = Post::where('pepperidge_inspired',1)->orderBy('id', 'desc')->get();

        return view('admin.inspired_content.index', [
            'posts' => $posts
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('admin.inspired_content.create');
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return Response
     */
    public function store(Request $request)
    {
        $rules = array(
            'comments'             => 'required',
        );

        $validator = \Validator::make(\Input::all(), $rules);

        if ($validator->fails()) {
            return redirect()->route('admin.inspired_content.create')
                ->withErrors($validator)
                ->withInput();
        } else {

            $image_url = $this->uploadFile($request, 'photo');
            $video_url = $this->uploadFile($request, 'video');

            $media_type = $video_url ? "video" : "image";

            $post_values = [
                'pepperidge_inspired' => 1,
                'author_name' => 'Respect the bun',
                'valid_entry' => 1,
                'approved' => 1,
                'media_type' => $media_type,
                'image' => $image_url,
                'image_thumb' => $image_url,
                'video' => $video_url,
                'network' => 'Pepperidge',
                'network_id' => time(),
                'post_date' => date('Y-m-d H:i:s')
            ];

            $post = Post::create(array_merge($request->all(),$post_values));

            $post->show_gallery = true;
            $post->approved = true;
            $post->reviewed = true;
            $post->save();


            // redirect
            \Session::flash('message', 'Successfully added post');
            return redirect()->route('admin.inspired_content.index');
        }
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        return redirect()->route('admin.inspired_content.index');
        /*$post = Post::find($id);

        return view('admin.inspired_content.show', [
            'post' => $post
        ]);*/
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        $post = Post::find($id);

        return view('admin.inspired_content.edit', [
            'post' => $post
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $post = Post::find($id);

        $rules = array(
            'comments'             => 'required',
        );
        $validator = \Validator::make(\Input::all(), $rules);

        if ($validator->fails()) {
            return redirect()->route('admin.inspired_content.show', [
                'post' => $post
            ])
                ->withErrors($validator)
                ->withInput();
        }

        $post_values = $request->all();

        if ($request->hasFile('file'))
        {
            $post_values['image'] = $this->uploadImage($request);
            $post_values['image_thumb'] = $post_values['image'];
        }

        $post->update($post_values);

        // redirect
        \Session::flash('message', 'Successfully updated post');
        return redirect()->route('admin.inspired_content.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        Post::destroy($id);
        \Session::flash('message', 'Inspiration post deleted');
        return redirect()->route('admin.inspired_content.index');
    }


    /**
     * Upload an image, save it to S3, and return the URL
     *
     * @param Request $request
     * @return string
     */
    public function uploadFile(Request $request, $name)
    {
        if( !$request->hasFile($name) ) {
            return null;
        }

        $image = $request->file($name);
        $fileHash = sha1_file($image->getRealPath());
        $fileKey = strtolower(config('app.project_code'). '/' .\App::environment().'/inspired-content/'.date('YmdHis').'-'.$fileHash.'.'.$image->getClientOriginalExtension());

        $s3 = Storage::disk('s3');
        $s3->put($fileKey, file_get_contents($image->getRealPath()));

        return "https://bm-projects-public.s3.amazonaws.com/" . $fileKey;
    }

}

source/resources/views/admin/inspired_content/create.blade.php
@extends('layout.admin')

@section('content')

    <div class="panel panel-default">
        <div class="panel-heading">
            Add Inspired Content
        </div>
        <div class="panel-body">
            <h3>Add Inspired Content</h3>

            {!! \Html::ul($errors->all()) !!}

            {!! Form::open(['url' => route('admin.inspired_content.store'), 'class' => 'form-horizontal', 'files' => true]) !!}
            <div class="form-group">
                {!! Form::label('comments', 'Comments', ['class' => 'col-sm-2 control-label']) !!}
                <div class="col-sm-10">
                    {!! Form::textarea('comments', Input::old('comments'), ['class' => 'form-control', 'required'=>'']) !!}
                </div>
            </div>

            <div class="form-group">
                {!! Form::label('video', 'Video', ['class' => 'col-sm-2 control-label']) !!}
                <div class="col-sm-10">
                    {!! Form::file('video', Input::old('video_url'), array('class' => 'form-control')) !!}
                    <div class="help-block">
                        (Videos should be .MP4 files with H264 encoding)
                    </div>
                </div>
            </div>

            <div class="form-group">
                {!! Form::label('photo', 'Photo', ['class' => 'col-sm-2 control-label']) !!}
                <div class="col-sm-10">
                    {!! Form::file('photo', Input::old('photo_url'), array('class' => 'form-control')) !!}
                    <div class="help-block">
                        (When adding videos, this photo will appear as the preview image)
                    </div>
                </div>
            </div>

            <div class="row form-footer">
                <div class="col-10-sm col-sm-offset-2">
                    {!! Form::submit('Add Post', ['class' => 'btn btn-primary']) !!}
                </div>
            </div>

            {!! Form::close() !!}
        </div>
    </div>

@endsection

source/resources/views/admin/inspired_content/edit.blade.php
@extends('layout.admin')

@section('content')

    <div class="panel panel-default">
        <div class="panel-heading">
            Add Inspired Content
        </div>
        <div class="panel-body">
            <h3>Add Inspired Content</h3>

            {!! \Html::ul($errors->all()) !!}

            {!! Form::open(['url' => route('admin.inspired_content.update', $post->id), 'class' => 'form-horizontal', 'files' => true, 'method' => 'put']) !!}

            <div class="form-group">
                {!! Form::label('comments', 'Comments', ['class' => 'col-sm-2 control-label']) !!}
                <div class="col-sm-10">
                    {!! Form::textarea('comments', $post->comments, ['class' => 'form-control', 'required'=>'']) !!}
                </div>
            </div>

            <div class="form-group">
                {!! Form::label('file', 'Current Photo', ['class' => 'col-sm-2 control-label']) !!}
                <div class="col-sm-10">
                    <img src="{{ $post->image }}" width="200" />
                </div>
            </div>

            <div class="form-group">
                {!! Form::label('file', 'Update Photo', ['class' => 'col-sm-2 control-label']) !!}
                <div class="col-sm-10">
                    {!! Form::file('file', Input::old('photo_url'), array('class' => 'form-control')) !!}
                </div>
            </div>

            <div class="row form-footer">
                <div class="col-10-sm col-sm-offset-2">
                    {!! Form::submit('Update Post', ['class' => 'btn btn-primary']) !!}
                </div>
            </div>

            {!! Form::close() !!}
        </div>
    </div>

@endsection

source/resources/views/admin/inspired_content/index.blade.php
@extends('layout.admin')

@section('content')

    <div class="social-posts panel panel-default">
        <div class="panel-heading"><span class="glyphicon glyphicon-asterisk"></span> Inspired Content</div>
        <div class="panel-body text-right">
            <a href="{{ route('admin.inspired_content.create') }}" class="btn btn-primary">
                <i class="fa fa-plus"></i>
                Add New Inspired Content
            </a>
        </div>

        <hr>

        <table class="table table-striped clearfix">
            <thead>
            <tr>
                <th class="col-xs-2" class="text-center">Image</th>
                <th class="col-xs-4">Content</th>
                <th class="col-xs-2">Post Date</th>
                <th class="col-xs-2">Actions</th>
            </tr>
            </thead>
            <tbody>
            @if( count($posts) == 0 )
            <tr>
                <td colspan="6" class="no-matches">No Matching Posts</td>
            </tr>
            @else
            @foreach( $posts as $p )
            <tr class="{{ $p->valid_entry === 0 ? "danger" : ""}}">
            <td>
                @if( $p->isImage() )
                <a class="social-image" href="{{ $p->image }}">
                    <img src="{{ $p->image }}" alt="" />
                </a>
                @elseif( $p->isVideo() )
                <a class="social-image" href="{{ $p->image }}">
                    <video width="320" height="320" controls>
                        <source src="{{ $p->video }}" type="video/mp4">
                        Your browser does not support the video tag.
                    </video>
                </a>
                @else
                N/A
                @endif
            </td>
            <td>
                {!! nl2br($p->comments) !!}
            </td>
            <td>
                {{ date("m/d/y g:i A", strtotime($p->post_date)) }}
            </td>
            <td>
                <a href="{{ route('admin.inspired_content.edit', $p) }}" class="btn btn-primary">Edit</a>
                {!! Form::open(['route' => ['admin.inspired_content.destroy', $p->id], 'method' => 'delete', 'class' => 'inline-block']) !!}
                <button type="submit" class="btn btn-danger btn-mini">Delete</button>
                {!! Form::close() !!}
            </td>
            </tr>
            @endforeach
            @endif
            </tbody>
        </table>

    </div>
@stop